"""add is_special to menu_items

Revision ID: fc2b35ef981c
Revises: ff984ab80d01
Create Date: 2026-07-03 13:12:37.409534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2b35ef981c'
down_revision: Union[str, Sequence[str], None] = 'ff984ab80d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('menu_items', sa.Column('is_special', sa.Boolean(), nullable=True))
    op.execute("UPDATE menu_items SET is_special = FALSE WHERE is_special IS NULL")
    op.alter_column('menu_items', 'is_special', nullable=False, server_default='false')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_special')
    # ### end Alembic commands ###
